import { paraglideVitePlugin } from '@inlang/paraglide-js';
import { cloudflare } from '@cloudflare/vite-plugin';
import { reactRouter } from '@react-router/dev/vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import oxlintPlugin from 'vite-plugin-oxlint';
import tailwindcss from '@tailwindcss/vite';
import babel from 'vite-plugin-babel';
import { defineConfig } from 'vite';
import dedent from 'dedent';

if (process.env.ZERO_COMPOSE_BUILD === 'true')
  Object.assign(globalThis, { __ZERO_ORIGIN__: 'http://localhost' });

const ReactCompilerConfig = {
  /* ... */
};

export default defineConfig({
  define:
    process.env.ZERO_COMPOSE_BUILD === 'true'
      ? {
          'import.meta.env.VITE_PUBLIC_APP_URL': 'globalThis.__ZERO_ORIGIN__',
          'import.meta.env.VITE_PUBLIC_BACKEND_URL': 'globalThis.__ZERO_ORIGIN__',
          'import.meta.env.VITE_PUBLIC_SELF_HOSTED': '"true"',
          'import.meta.env.VITE_PUBLIC_SELF_HOSTED_AUTH': '"required"',
        }
      : {},
  plugins: [
    oxlintPlugin({
      params:
        '--ignore-pattern=**/node_modules/** --ignore-pattern=**/build/** --ignore-pattern=**/.react-router/**',
    }),
    reactRouter(),
    cloudflare(),
    babel({
      filter: /\.[jt]sx?$/,
      exclude: /node_modules/,
      babelConfig: {
        sourceMaps: true,
        presets: ['@babel/preset-typescript'], // if you use TypeScript
        plugins: [['babel-plugin-react-compiler', ReactCompilerConfig]],
      },
    }),
    tsconfigPaths(),
    tailwindcss(),
    {
      name: 'add-headers',
      applyToEnvironment: (env) => env.name === 'client',
      generateBundle() {
        this.emitFile({
          fileName: '_headers',
          type: 'asset',
          source: dedent`
            # Autogenerated

            /assets/*
              ! Cache-Control
                Cache-Control: public, immutable, max-age=31536000
          `,
        });
      },
    },
    paraglideVitePlugin({
      project: './project.inlang',
      outdir: './paraglide',
      strategy: ['cookie', 'custom-browserLanguage', 'baseLocale'],
    }),
  ],
  server: {
    port: 3000,
    warmup: {
      clientFiles: ['./app/**/*', './components/**/*'],
    },
  },
  //   ssr: {
  //     optimizeDeps: {
  //       include: ['novel', '@tiptap/extension-placeholder'],
  //     },
  //   },
  esbuild: {
    pure: ['console.log'],
  },
  build: {
    sourcemap: false,
  },
  resolve: {
    alias: {
      tslib: 'tslib/tslib.es6.js',
    },
  },
});
